version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    
  frontend:
    build:
      context: ./frontend
    ports:
      - "5713:80"
    networks:
      - mynetwork
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge